apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app-dev
  namespace: argocd
spec:
  project: default

  spec:
  source:
    path: go-web-app-chart
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true