apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Tarakadambi/go-web-app-devops.git
    targetRevision: main
    path: go-web-app-chart
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true